
site_name: Shanshan's Blog
use_directory_urls: false

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: static/avatar.jpg


nav:
    - 首页: index.md

    - 常用工具:
      - mkdocs + GitHub 搭建文档网站: util/20220307-mkdocs.md
      - 项目收工小技巧: util/20220322-项目收工小技巧.md
      - SSH 加速下载 GitHub 项目: util/20220406-ssh.md
      - git 常用指令: util/20220312-git.md
      - 关于 PR CI: util/20220411-CI.md
      - VSCode debug 工具: util/20220413-vscode debug tip.md

    - 框架组:
      - 技巧总结: engineering/技巧总结.md
      - 22 core dumped: engineering/20220406-22 core dumped.md
      - 23 ninja build stopped: engineering/20220408-23 ninja build stopped.md
      - 添加half: engineering/20220407-添加half.md
      - 添加deconv: engineering/20220408-添加deconv.md
      - AutoTest: engineering/20220411-autotest.md
      - 添加nn.init.orthogonal: engineering/20220412-orthogonal_.md

    - 云平台:
      - 对齐过程经验沉淀: onecloud/20220408-对齐过程经验沉淀.md
      - 云平台使用注意事项: onecloud/20220322-云平台使用注意事项.md
      - Flask 加载不出 js 等静态文件: onecloud/20220322-Flask 加载不出 js 等静态文件.md

    - PR: works.md
